PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX uwa: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT * WHERE {
      uwa:Product14971 ?p ?c .
      uwa:Product14300 ?p ?d .
} LIMIT 100